<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\JobApplyAI.Core\JobApplyAI.Core.csproj" />
    <ProjectReference Include="..\JobApplyAI.Application\JobApplyAI.Application.csproj" />
    <ProjectReference Include="..\JobApplyAI.Infrastructure\JobApplyAI.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Identity.Web" Version="4.14.2" />
    <PackageReference Include="Microsoft.Identity.Web.UI" Version="4.14.2" />
    <PackageReference Include="MudBlazor" Version="9.9.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>7267cfda-91be-491f-bd3c-d52c881a1969</UserSecretsId>
  </PropertyGroup>

</Project>
